spring.application.name=music-store
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=music_store
spring.datasource.password=mahedee
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver